language: go
go:
  - "1.13"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test_db;'
before_script:
  - mysql -D test_db < model.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)
script: go test -v  -coverprofile=coverage.txt ./...
